name: autex

description: "Aplicacion para el control y gestion de vehiculos siendo utilizada con funciones de notificacion para recordatorio."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencias para el manejo de UI, Iconos y Material Design
  cupertino_icons: ^1.0.8

  # Dependencias para el manejo de estado para la network consumo de requests API's
  http: ^1.1.0

  # Base de datos o storage
  shared_preferences: ^2.2.2

  #tiempo y fecha
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Configuración icon launcher
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
